// flow-typed signature: 311cd573c61854e7ec463d5463cbdbdf
// flow-typed version: <<STUB>>/@mauron85/react-native-background-geolocation_v0.6.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mauron85/react-native-background-geolocation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mauron85/react-native-background-geolocation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mauron85/react-native-background-geolocation/BackgroundGeolocation.Promise' {
  declare module.exports: any;
}

declare module '@mauron85/react-native-background-geolocation/ios/common/scripts/xcode-refactor' {
  declare module.exports: any;
}

declare module '@mauron85/react-native-background-geolocation/ios/pkgversion' {
  declare module.exports: any;
}

declare module '@mauron85/react-native-background-geolocation/react-native.config' {
  declare module.exports: any;
}

declare module '@mauron85/react-native-background-geolocation/scripts/config' {
  declare module.exports: any;
}

declare module '@mauron85/react-native-background-geolocation/scripts/isInstalled' {
  declare module.exports: any;
}

declare module '@mauron85/react-native-background-geolocation/scripts/postlink' {
  declare module.exports: any;
}

declare module '@mauron85/react-native-background-geolocation/scripts/postunlink' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mauron85/react-native-background-geolocation/BackgroundGeolocation.Promise.js' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation/BackgroundGeolocation.Promise'>;
}
declare module '@mauron85/react-native-background-geolocation/index' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation'>;
}
declare module '@mauron85/react-native-background-geolocation/index.js' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation'>;
}
declare module '@mauron85/react-native-background-geolocation/ios/common/scripts/xcode-refactor.js' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation/ios/common/scripts/xcode-refactor'>;
}
declare module '@mauron85/react-native-background-geolocation/ios/pkgversion.js' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation/ios/pkgversion'>;
}
declare module '@mauron85/react-native-background-geolocation/react-native.config.js' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation/react-native.config'>;
}
declare module '@mauron85/react-native-background-geolocation/scripts/config.js' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation/scripts/config'>;
}
declare module '@mauron85/react-native-background-geolocation/scripts/isInstalled.js' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation/scripts/isInstalled'>;
}
declare module '@mauron85/react-native-background-geolocation/scripts/postlink.js' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation/scripts/postlink'>;
}
declare module '@mauron85/react-native-background-geolocation/scripts/postunlink.js' {
  declare module.exports: $Exports<'@mauron85/react-native-background-geolocation/scripts/postunlink'>;
}
