// @flow

// flow-typed signature: 4e662f74d6e19ff5cd450480e1b20634
// flow-typed version: <<STUB>>/@turf/bbox-polygon_v6.0.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/bbox-polygon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/bbox-polygon' {
  import type { BBox, Properties, Id, Polygon } from '@turf/helpers';
  declare module.exports: (BBox, ?{| properties: Properties, id: Id |}) => Feature<Polygon>;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module '@turf/bbox-polygon/index' {
  declare module.exports: $Exports<'@turf/bbox-polygon'>;
}
declare module '@turf/bbox-polygon/index.js' {
  declare module.exports: $Exports<'@turf/bbox-polygon'>;
}
