// @flow

// flow-typed signature: 1e29292a69226cd8e3b0a85ce16b26df
// flow-typed version: <<STUB>>/@turf/bbox_v6.0.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/bbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/bbox' {
  import type { GeoJSONObject, BBox2d } from '@turf/helpers';
  declare module.exports: GeoJSONObject => BBox2d;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module '@turf/bbox/index' {
  declare module.exports: $Exports<'@turf/bbox'>;
}
declare module '@turf/bbox/index.js' {
  declare module.exports: $Exports<'@turf/bbox'>;
}
