// @flow

// flow-typed signature: 3e3027e9b9db8be56ad4b6c538641775
// flow-typed version: <<STUB>>/@turf/intersect_v6.1.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/intersect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/intersect' {
  import type { Feature, GeometryObject, Polygon } from '@turf/helpers';
  declare module.exports: (poly1: Feature<Polygon>, poly2: Feature<Polygon>) => ?Feature<GeometryObject>;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module '@turf/intersect/index' {
  declare module.exports: $Exports<'@turf/intersect'>;
}
declare module '@turf/intersect/index.js' {
  declare module.exports: $Exports<'@turf/intersect'>;
}
