// flow-typed signature: b42c0dd3ad4751a4437c11b7617a80b7
// flow-typed version: <<STUB>>/@turf/kinks_v6.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/kinks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/kinks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/kinks/index' {
  declare module.exports: $Exports<'@turf/kinks'>;
}
declare module '@turf/kinks/index.js' {
  declare module.exports: $Exports<'@turf/kinks'>;
}
