// flow-typed signature: c2962ffcf2c90d4121be2d2d8ce146f1
// flow-typed version: <<STUB>>/boundingbox_v0.1.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boundingbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boundingbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boundingbox/BoundingBox' {
  declare module.exports: any;
}

declare module 'boundingbox/test/test_bounds' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boundingbox/BoundingBox.js' {
  declare module.exports: $Exports<'boundingbox/BoundingBox'>;
}
declare module 'boundingbox/test/test_bounds.js' {
  declare module.exports: $Exports<'boundingbox/test/test_bounds'>;
}
