// flow-typed signature: 42d3a0ca72a6ec507b0f5f4313bbaa7a
// flow-typed version: <<STUB>>/formatcoords_v1.1.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'formatcoords'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'formatcoords' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'formatcoords/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'formatcoords/index' {
  declare module.exports: $Exports<'formatcoords'>;
}
declare module 'formatcoords/index.js' {
  declare module.exports: $Exports<'formatcoords'>;
}
declare module 'formatcoords/test/test.js' {
  declare module.exports: $Exports<'formatcoords/test/test'>;
}
