// flow-typed signature: 78a1365f4ba4c9b96a09ea7399062b78
// flow-typed version: <<STUB>>/geojson-polygon-self-intersections_v1.2.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geojson-polygon-self-intersections'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geojson-polygon-self-intersections' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'geojson-polygon-self-intersections/index' {
  declare module.exports: $Exports<'geojson-polygon-self-intersections'>;
}
declare module 'geojson-polygon-self-intersections/index.js' {
  declare module.exports: $Exports<'geojson-polygon-self-intersections'>;
}
