// flow-typed signature: 5d69f9b772cd11bd087ce1b32973e5e0
// flow-typed version: <<STUB>>/geokdbush_v1.1.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geokdbush'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geokdbush' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geokdbush/bench/bench-geokdbush' {
  declare module.exports: any;
}

declare module 'geokdbush/bench/bench-naive' {
  declare module.exports: any;
}

declare module 'geokdbush/bench/bench-sphere-knn' {
  declare module.exports: any;
}

declare module 'geokdbush/debug' {
  declare module.exports: any;
}

declare module 'geokdbush/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geokdbush/bench/bench-geokdbush.js' {
  declare module.exports: $Exports<'geokdbush/bench/bench-geokdbush'>;
}
declare module 'geokdbush/bench/bench-naive.js' {
  declare module.exports: $Exports<'geokdbush/bench/bench-naive'>;
}
declare module 'geokdbush/bench/bench-sphere-knn.js' {
  declare module.exports: $Exports<'geokdbush/bench/bench-sphere-knn'>;
}
declare module 'geokdbush/debug.js' {
  declare module.exports: $Exports<'geokdbush/debug'>;
}
declare module 'geokdbush/index' {
  declare module.exports: $Exports<'geokdbush'>;
}
declare module 'geokdbush/index.js' {
  declare module.exports: $Exports<'geokdbush'>;
}
declare module 'geokdbush/test.js' {
  declare module.exports: $Exports<'geokdbush/test'>;
}
