// flow-typed signature: 8603ffbeb636366ebda6092bc0880eda
// flow-typed version: <<STUB>>/json2csv_v4.4.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json2csv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json2csv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json2csv/bin/json2csv' {
  declare module.exports: any;
}

declare module 'json2csv/bin/utils/parseNdjson' {
  declare module.exports: any;
}

declare module 'json2csv/bin/utils/TablePrinter' {
  declare module.exports: any;
}

declare module 'json2csv/dist/json2csv.cjs' {
  declare module.exports: any;
}

declare module 'json2csv/dist/json2csv.esm' {
  declare module.exports: any;
}

declare module 'json2csv/dist/json2csv.umd' {
  declare module.exports: any;
}

declare module 'json2csv/lib/json2csv' {
  declare module.exports: any;
}

declare module 'json2csv/lib/JSON2CSVAsyncParser' {
  declare module.exports: any;
}

declare module 'json2csv/lib/JSON2CSVBase' {
  declare module.exports: any;
}

declare module 'json2csv/lib/JSON2CSVParser' {
  declare module.exports: any;
}

declare module 'json2csv/lib/JSON2CSVTransform' {
  declare module.exports: any;
}

declare module 'json2csv/lib/utils' {
  declare module.exports: any;
}

declare module 'json2csv/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json2csv/bin/json2csv.js' {
  declare module.exports: $Exports<'json2csv/bin/json2csv'>;
}
declare module 'json2csv/bin/utils/parseNdjson.js' {
  declare module.exports: $Exports<'json2csv/bin/utils/parseNdjson'>;
}
declare module 'json2csv/bin/utils/TablePrinter.js' {
  declare module.exports: $Exports<'json2csv/bin/utils/TablePrinter'>;
}
declare module 'json2csv/dist/json2csv.cjs.js' {
  declare module.exports: $Exports<'json2csv/dist/json2csv.cjs'>;
}
declare module 'json2csv/dist/json2csv.esm.js' {
  declare module.exports: $Exports<'json2csv/dist/json2csv.esm'>;
}
declare module 'json2csv/dist/json2csv.umd.js' {
  declare module.exports: $Exports<'json2csv/dist/json2csv.umd'>;
}
declare module 'json2csv/lib/json2csv.js' {
  declare module.exports: $Exports<'json2csv/lib/json2csv'>;
}
declare module 'json2csv/lib/JSON2CSVAsyncParser.js' {
  declare module.exports: $Exports<'json2csv/lib/JSON2CSVAsyncParser'>;
}
declare module 'json2csv/lib/JSON2CSVBase.js' {
  declare module.exports: $Exports<'json2csv/lib/JSON2CSVBase'>;
}
declare module 'json2csv/lib/JSON2CSVParser.js' {
  declare module.exports: $Exports<'json2csv/lib/JSON2CSVParser'>;
}
declare module 'json2csv/lib/JSON2CSVTransform.js' {
  declare module.exports: $Exports<'json2csv/lib/JSON2CSVTransform'>;
}
declare module 'json2csv/lib/utils.js' {
  declare module.exports: $Exports<'json2csv/lib/utils'>;
}
declare module 'json2csv/rollup.config.js' {
  declare module.exports: $Exports<'json2csv/rollup.config'>;
}
