// flow-typed signature: f64e7d02516eb3467431ae7211335ad3
// flow-typed version: <<STUB>>/jsonapi-serializer_v3.6.4/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonapi-serializer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonapi-serializer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonapi-serializer/browserify/jsonapi-serializer' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/examples/express/app' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/examples/express/routes' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/examples/express/routes/users' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/examples/express/serializers/user' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/Gruntfile' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/lib/collection-serializer' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/lib/deserializer-utils' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/lib/deserializer' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/lib/error-utils' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/lib/error' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/lib/inflector' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/lib/serializer-utils' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/lib/serializer' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/test/deserializer' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/test/error' {
  declare module.exports: any;
}

declare module 'jsonapi-serializer/test/serializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonapi-serializer/browserify/jsonapi-serializer.js' {
  declare module.exports: $Exports<'jsonapi-serializer/browserify/jsonapi-serializer'>;
}
declare module 'jsonapi-serializer/examples/express/app.js' {
  declare module.exports: $Exports<'jsonapi-serializer/examples/express/app'>;
}
declare module 'jsonapi-serializer/examples/express/routes/index' {
  declare module.exports: $Exports<'jsonapi-serializer/examples/express/routes'>;
}
declare module 'jsonapi-serializer/examples/express/routes/index.js' {
  declare module.exports: $Exports<'jsonapi-serializer/examples/express/routes'>;
}
declare module 'jsonapi-serializer/examples/express/routes/users.js' {
  declare module.exports: $Exports<'jsonapi-serializer/examples/express/routes/users'>;
}
declare module 'jsonapi-serializer/examples/express/serializers/user.js' {
  declare module.exports: $Exports<'jsonapi-serializer/examples/express/serializers/user'>;
}
declare module 'jsonapi-serializer/Gruntfile.js' {
  declare module.exports: $Exports<'jsonapi-serializer/Gruntfile'>;
}
declare module 'jsonapi-serializer/index' {
  declare module.exports: $Exports<'jsonapi-serializer'>;
}
declare module 'jsonapi-serializer/index.js' {
  declare module.exports: $Exports<'jsonapi-serializer'>;
}
declare module 'jsonapi-serializer/lib/collection-serializer.js' {
  declare module.exports: $Exports<'jsonapi-serializer/lib/collection-serializer'>;
}
declare module 'jsonapi-serializer/lib/deserializer-utils.js' {
  declare module.exports: $Exports<'jsonapi-serializer/lib/deserializer-utils'>;
}
declare module 'jsonapi-serializer/lib/deserializer.js' {
  declare module.exports: $Exports<'jsonapi-serializer/lib/deserializer'>;
}
declare module 'jsonapi-serializer/lib/error-utils.js' {
  declare module.exports: $Exports<'jsonapi-serializer/lib/error-utils'>;
}
declare module 'jsonapi-serializer/lib/error.js' {
  declare module.exports: $Exports<'jsonapi-serializer/lib/error'>;
}
declare module 'jsonapi-serializer/lib/inflector.js' {
  declare module.exports: $Exports<'jsonapi-serializer/lib/inflector'>;
}
declare module 'jsonapi-serializer/lib/serializer-utils.js' {
  declare module.exports: $Exports<'jsonapi-serializer/lib/serializer-utils'>;
}
declare module 'jsonapi-serializer/lib/serializer.js' {
  declare module.exports: $Exports<'jsonapi-serializer/lib/serializer'>;
}
declare module 'jsonapi-serializer/test/deserializer.js' {
  declare module.exports: $Exports<'jsonapi-serializer/test/deserializer'>;
}
declare module 'jsonapi-serializer/test/error.js' {
  declare module.exports: $Exports<'jsonapi-serializer/test/error'>;
}
declare module 'jsonapi-serializer/test/serializer.js' {
  declare module.exports: $Exports<'jsonapi-serializer/test/serializer'>;
}
