// flow-typed signature: 0c02ce6d40aa7540a7346ad6fa2822f6
// flow-typed version: <<STUB>>/kdbush_v1.0.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kdbush'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kdbush' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kdbush/bench' {
  declare module.exports: any;
}

declare module 'kdbush/src/kdbush' {
  declare module.exports: any;
}

declare module 'kdbush/src/range' {
  declare module.exports: any;
}

declare module 'kdbush/src/sort' {
  declare module.exports: any;
}

declare module 'kdbush/src/within' {
  declare module.exports: any;
}

declare module 'kdbush/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kdbush/bench.js' {
  declare module.exports: $Exports<'kdbush/bench'>;
}
declare module 'kdbush/src/kdbush.js' {
  declare module.exports: $Exports<'kdbush/src/kdbush'>;
}
declare module 'kdbush/src/range.js' {
  declare module.exports: $Exports<'kdbush/src/range'>;
}
declare module 'kdbush/src/sort.js' {
  declare module.exports: $Exports<'kdbush/src/sort'>;
}
declare module 'kdbush/src/within.js' {
  declare module.exports: $Exports<'kdbush/src/within'>;
}
declare module 'kdbush/test.js' {
  declare module.exports: $Exports<'kdbush/test'>;
}
