// flow-typed signature: c519640da21ecf9aa588bb2e587415cd
// flow-typed version: <<STUB>>/react-native-dialogs_v1.1.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-dialogs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-dialogs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-dialogs/DialogAndroid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-dialogs/DialogAndroid.js' {
  declare module.exports: $Exports<'react-native-dialogs/DialogAndroid'>;
}
declare module 'react-native-dialogs/index' {
  declare module.exports: $Exports<'react-native-dialogs'>;
}
declare module 'react-native-dialogs/index.js' {
  declare module.exports: $Exports<'react-native-dialogs'>;
}
