// flow-typed signature: ae2f5564b3ac7fa681265195adfe33ba
// flow-typed version: <<STUB>>/react-native-compass-heading_v1.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-compass-heading'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-compass-heading' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-compass-heading/index' {
  declare module.exports: $Exports<'react-native-compass-heading'>;
}
declare module 'react-native-compass-heading/index.js' {
  declare module.exports: $Exports<'react-native-compass-heading'>;
}
