// flow-typed signature: 228b0be3cd2a849333723ab6f7a7100c
// flow-typed version: <<STUB>>/react-native-get-random-values_v1.3.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-get-random-values'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-get-random-values' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-get-random-values/index.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-get-random-values/index' {
  declare module.exports: $Exports<'react-native-get-random-values'>;
}
declare module 'react-native-get-random-values/index.js' {
  declare module.exports: $Exports<'react-native-get-random-values'>;
}
declare module 'react-native-get-random-values/index.web.js' {
  declare module.exports: $Exports<'react-native-get-random-values/index.web'>;
}
