// flow-typed signature: 8fbdbcd9835a0369ff7fdbad9c6b8bde
// flow-typed version: <<STUB>>/react-native-actions-sheet_v0.1.9/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-actions-sheet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-actions-sheet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-actions-sheet/src' {
  declare module.exports: any;
}

declare module 'react-native-actions-sheet/src/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-actions-sheet/index' {
  declare module.exports: $Exports<'react-native-actions-sheet'>;
}
declare module 'react-native-actions-sheet/index.js' {
  declare module.exports: $Exports<'react-native-actions-sheet'>;
}
declare module 'react-native-actions-sheet/src/index' {
  declare module.exports: $Exports<'react-native-actions-sheet/src'>;
}
declare module 'react-native-actions-sheet/src/index.js' {
  declare module.exports: $Exports<'react-native-actions-sheet/src'>;
}
declare module 'react-native-actions-sheet/src/styles.js' {
  declare module.exports: $Exports<'react-native-actions-sheet/src/styles'>;
}
