// flow-typed signature: c04e40687eae5bbb4270c8718aec0284
// flow-typed version: <<STUB>>/react-native-hyperlink_v0.0.14/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-hyperlink'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-hyperlink' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-hyperlink/dist' {
  declare module.exports: any;
}

declare module 'react-native-hyperlink/src/Hyperlink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-hyperlink/dist/index' {
  declare module.exports: $Exports<'react-native-hyperlink/dist'>;
}
declare module 'react-native-hyperlink/dist/index.js' {
  declare module.exports: $Exports<'react-native-hyperlink/dist'>;
}
declare module 'react-native-hyperlink/src/Hyperlink.js' {
  declare module.exports: $Exports<'react-native-hyperlink/src/Hyperlink'>;
}
