// flow-typed signature: 06e2ed0e52cd39af4db2c94a5393235d
// flow-typed version: <<STUB>>/react-native-safe-area_v0.5.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safe-area'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safe-area' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safe-area/lib' {
  declare module.exports: any;
}

declare module 'react-native-safe-area/lib/SafeArea.android' {
  declare module.exports: any;
}

declare module 'react-native-safe-area/lib/SafeArea.ios' {
  declare module.exports: any;
}

declare module 'react-native-safe-area/lib/TypeDefinition' {
  declare module.exports: any;
}

declare module 'react-native-safe-area/lib/withSafeArea' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safe-area/lib/index' {
  declare module.exports: $Exports<'react-native-safe-area/lib'>;
}
declare module 'react-native-safe-area/lib/index.js' {
  declare module.exports: $Exports<'react-native-safe-area/lib'>;
}
declare module 'react-native-safe-area/lib/SafeArea.android.js' {
  declare module.exports: $Exports<'react-native-safe-area/lib/SafeArea.android'>;
}
declare module 'react-native-safe-area/lib/SafeArea.ios.js' {
  declare module.exports: $Exports<'react-native-safe-area/lib/SafeArea.ios'>;
}
declare module 'react-native-safe-area/lib/TypeDefinition.js' {
  declare module.exports: $Exports<'react-native-safe-area/lib/TypeDefinition'>;
}
declare module 'react-native-safe-area/lib/withSafeArea.js' {
  declare module.exports: $Exports<'react-native-safe-area/lib/withSafeArea'>;
}
