// flow-typed signature: cce9eccc7fbeaeeaa7f28248bdf256d2
// flow-typed version: <<STUB>>/react-native-scrollable-tab-view_v1.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-scrollable-tab-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-scrollable-tab-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-scrollable-tab-view/Button.android' {
  declare module.exports: any;
}

declare module 'react-native-scrollable-tab-view/Button.ios' {
  declare module.exports: any;
}

declare module 'react-native-scrollable-tab-view/DefaultTabBar' {
  declare module.exports: any;
}

declare module 'react-native-scrollable-tab-view/SceneComponent' {
  declare module.exports: any;
}

declare module 'react-native-scrollable-tab-view/ScrollableTabBar' {
  declare module.exports: any;
}

declare module 'react-native-scrollable-tab-view/StaticContainer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-scrollable-tab-view/Button.android.js' {
  declare module.exports: $Exports<'react-native-scrollable-tab-view/Button.android'>;
}
declare module 'react-native-scrollable-tab-view/Button.ios.js' {
  declare module.exports: $Exports<'react-native-scrollable-tab-view/Button.ios'>;
}
declare module 'react-native-scrollable-tab-view/DefaultTabBar.js' {
  declare module.exports: $Exports<'react-native-scrollable-tab-view/DefaultTabBar'>;
}
declare module 'react-native-scrollable-tab-view/index' {
  declare module.exports: $Exports<'react-native-scrollable-tab-view'>;
}
declare module 'react-native-scrollable-tab-view/index.js' {
  declare module.exports: $Exports<'react-native-scrollable-tab-view'>;
}
declare module 'react-native-scrollable-tab-view/SceneComponent.js' {
  declare module.exports: $Exports<'react-native-scrollable-tab-view/SceneComponent'>;
}
declare module 'react-native-scrollable-tab-view/ScrollableTabBar.js' {
  declare module.exports: $Exports<'react-native-scrollable-tab-view/ScrollableTabBar'>;
}
declare module 'react-native-scrollable-tab-view/StaticContainer.js' {
  declare module.exports: $Exports<'react-native-scrollable-tab-view/StaticContainer'>;
}
