// flow-typed signature: 038e282a50834cf70b5e5ca923be6b7e
// flow-typed version: <<STUB>>/react-native-maps_v0.26.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-maps/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/AnimatedRegion' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/decorateMapComponent' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/Geojson' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapCallout' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapCalloutSubview' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapCircle' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapHeatmap' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapLocalTile' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapMarker' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapOverlay' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapPolygon' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapPolyline' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapUrlTile' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapView' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/MapWMSTile' {
  declare module.exports: any;
}

declare module 'react-native-maps/lib/components/ProviderConstants' {
  declare module.exports: any;
}

declare module 'react-native-maps/metro.config' {
  declare module.exports: any;
}

declare module 'react-native-maps/react-native.config' {
  declare module.exports: any;
}

declare module 'react-native-maps/rn-cli.config' {
  declare module.exports: any;
}

declare module 'react-native-maps/scripts/update-version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-maps/babel.config.js' {
  declare module.exports: $Exports<'react-native-maps/babel.config'>;
}
declare module 'react-native-maps/index' {
  declare module.exports: $Exports<'react-native-maps'>;
}
declare module 'react-native-maps/index.js' {
  declare module.exports: $Exports<'react-native-maps'>;
}
declare module 'react-native-maps/lib/components/AnimatedRegion.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/AnimatedRegion'>;
}
declare module 'react-native-maps/lib/components/decorateMapComponent.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/decorateMapComponent'>;
}
declare module 'react-native-maps/lib/components/Geojson.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/Geojson'>;
}
declare module 'react-native-maps/lib/components/MapCallout.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapCallout'>;
}
declare module 'react-native-maps/lib/components/MapCalloutSubview.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapCalloutSubview'>;
}
declare module 'react-native-maps/lib/components/MapCircle.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapCircle'>;
}
declare module 'react-native-maps/lib/components/MapHeatmap.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapHeatmap'>;
}
declare module 'react-native-maps/lib/components/MapLocalTile.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapLocalTile'>;
}
declare module 'react-native-maps/lib/components/MapMarker.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapMarker'>;
}
declare module 'react-native-maps/lib/components/MapOverlay.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapOverlay'>;
}
declare module 'react-native-maps/lib/components/MapPolygon.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapPolygon'>;
}
declare module 'react-native-maps/lib/components/MapPolyline.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapPolyline'>;
}
declare module 'react-native-maps/lib/components/MapUrlTile.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapUrlTile'>;
}
declare module 'react-native-maps/lib/components/MapView.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapView'>;
}
declare module 'react-native-maps/lib/components/MapWMSTile.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/MapWMSTile'>;
}
declare module 'react-native-maps/lib/components/ProviderConstants.js' {
  declare module.exports: $Exports<'react-native-maps/lib/components/ProviderConstants'>;
}
declare module 'react-native-maps/metro.config.js' {
  declare module.exports: $Exports<'react-native-maps/metro.config'>;
}
declare module 'react-native-maps/react-native.config.js' {
  declare module.exports: $Exports<'react-native-maps/react-native.config'>;
}
declare module 'react-native-maps/rn-cli.config.js' {
  declare module.exports: $Exports<'react-native-maps/rn-cli.config'>;
}
declare module 'react-native-maps/scripts/update-version.js' {
  declare module.exports: $Exports<'react-native-maps/scripts/update-version'>;
}
