// flow-typed signature: 0ec217efb85c4b4e56452494e2ae1a41
// flow-typed version: <<STUB>>/react-native-zip-archive_v5.0.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-zip-archive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-zip-archive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-zip-archive/index' {
  declare module.exports: $Exports<'react-native-zip-archive'>;
}
declare module 'react-native-zip-archive/index.js' {
  declare module.exports: $Exports<'react-native-zip-archive'>;
}
