// flow-typed signature: 8ecfdce731a9b8068a808fce9ad3d381
// flow-typed version: <<STUB>>/react-native-app-auth_v5.0.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-app-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-app-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-app-auth/index' {
  declare module.exports: $Exports<'react-native-app-auth'>;
}
declare module 'react-native-app-auth/index.js' {
  declare module.exports: $Exports<'react-native-app-auth'>;
}
