// flow-typed signature: 1f388a57d8f5fa2e25c5ff057622c3ed
// flow-typed version: <<STUB>>/react-native-timer_v1.3.6/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-timer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-timer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-timer/lib' {
  declare module.exports: any;
}

declare module 'react-native-timer/src' {
  declare module.exports: any;
}

declare module 'react-native-timer/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-timer/lib/index' {
  declare module.exports: $Exports<'react-native-timer/lib'>;
}
declare module 'react-native-timer/lib/index.js' {
  declare module.exports: $Exports<'react-native-timer/lib'>;
}
declare module 'react-native-timer/src/index' {
  declare module.exports: $Exports<'react-native-timer/src'>;
}
declare module 'react-native-timer/src/index.js' {
  declare module.exports: $Exports<'react-native-timer/src'>;
}
declare module 'react-native-timer/test/main.js' {
  declare module.exports: $Exports<'react-native-timer/test/main'>;
}
