// flow-typed signature: a305f3f8ad4cd4b7daa789061956f11a
// flow-typed version: <<STUB>>/realm_v5.0.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'realm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'realm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'realm/lib/browser/async-open-task' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/base64' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/collections' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/constants' {
  declare module.exports: any;
}

declare module 'realm/lib/browser' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/lists' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/objects' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/results' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/rpc' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/session' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/subscription' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/user' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/util' {
  declare module.exports: any;
}

declare module 'realm/lib/collection-methods' {
  declare module.exports: any;
}

declare module 'realm/lib/errors' {
  declare module.exports: any;
}

declare module 'realm/lib/extensions' {
  declare module.exports: any;
}

declare module 'realm/lib' {
  declare module.exports: any;
}

declare module 'realm/lib/notification-worker' {
  declare module.exports: any;
}

declare module 'realm/lib/notifier' {
  declare module.exports: any;
}

declare module 'realm/lib/permission-api' {
  declare module.exports: any;
}

declare module 'realm/lib/submit-analytics' {
  declare module.exports: any;
}

declare module 'realm/lib/user-methods' {
  declare module.exports: any;
}

declare module 'realm/lib/worker' {
  declare module.exports: any;
}

declare module 'realm/react-native.config' {
  declare module.exports: any;
}

declare module 'realm/react-native' {
  declare module.exports: any;
}

declare module 'realm/react-native/listview' {
  declare module.exports: any;
}

declare module 'realm/scripts/check-environment' {
  declare module.exports: any;
}

declare module 'realm/scripts/download-realm' {
  declare module.exports: any;
}

declare module 'realm/scripts/handle-license-check' {
  declare module.exports: any;
}

declare module 'realm/scripts/prepublish' {
  declare module.exports: any;
}

declare module 'realm/scripts/react-tests-android' {
  declare module.exports: any;
}

declare module 'realm/scripts/test-ros-server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'realm/lib/browser/async-open-task.js' {
  declare module.exports: $Exports<'realm/lib/browser/async-open-task'>;
}
declare module 'realm/lib/browser/base64.js' {
  declare module.exports: $Exports<'realm/lib/browser/base64'>;
}
declare module 'realm/lib/browser/collections.js' {
  declare module.exports: $Exports<'realm/lib/browser/collections'>;
}
declare module 'realm/lib/browser/constants.js' {
  declare module.exports: $Exports<'realm/lib/browser/constants'>;
}
declare module 'realm/lib/browser/index' {
  declare module.exports: $Exports<'realm/lib/browser'>;
}
declare module 'realm/lib/browser/index.js' {
  declare module.exports: $Exports<'realm/lib/browser'>;
}
declare module 'realm/lib/browser/lists.js' {
  declare module.exports: $Exports<'realm/lib/browser/lists'>;
}
declare module 'realm/lib/browser/objects.js' {
  declare module.exports: $Exports<'realm/lib/browser/objects'>;
}
declare module 'realm/lib/browser/results.js' {
  declare module.exports: $Exports<'realm/lib/browser/results'>;
}
declare module 'realm/lib/browser/rpc.js' {
  declare module.exports: $Exports<'realm/lib/browser/rpc'>;
}
declare module 'realm/lib/browser/session.js' {
  declare module.exports: $Exports<'realm/lib/browser/session'>;
}
declare module 'realm/lib/browser/subscription.js' {
  declare module.exports: $Exports<'realm/lib/browser/subscription'>;
}
declare module 'realm/lib/browser/user.js' {
  declare module.exports: $Exports<'realm/lib/browser/user'>;
}
declare module 'realm/lib/browser/util.js' {
  declare module.exports: $Exports<'realm/lib/browser/util'>;
}
declare module 'realm/lib/collection-methods.js' {
  declare module.exports: $Exports<'realm/lib/collection-methods'>;
}
declare module 'realm/lib/errors.js' {
  declare module.exports: $Exports<'realm/lib/errors'>;
}
declare module 'realm/lib/extensions.js' {
  declare module.exports: $Exports<'realm/lib/extensions'>;
}
declare module 'realm/lib/index' {
  declare module.exports: $Exports<'realm/lib'>;
}
declare module 'realm/lib/index.js' {
  declare module.exports: $Exports<'realm/lib'>;
}
declare module 'realm/lib/notification-worker.js' {
  declare module.exports: $Exports<'realm/lib/notification-worker'>;
}
declare module 'realm/lib/notifier.js' {
  declare module.exports: $Exports<'realm/lib/notifier'>;
}
declare module 'realm/lib/permission-api.js' {
  declare module.exports: $Exports<'realm/lib/permission-api'>;
}
declare module 'realm/lib/submit-analytics.js' {
  declare module.exports: $Exports<'realm/lib/submit-analytics'>;
}
declare module 'realm/lib/user-methods.js' {
  declare module.exports: $Exports<'realm/lib/user-methods'>;
}
declare module 'realm/lib/worker.js' {
  declare module.exports: $Exports<'realm/lib/worker'>;
}
declare module 'realm/react-native.config.js' {
  declare module.exports: $Exports<'realm/react-native.config'>;
}
declare module 'realm/react-native/index' {
  declare module.exports: $Exports<'realm/react-native'>;
}
declare module 'realm/react-native/index.js' {
  declare module.exports: $Exports<'realm/react-native'>;
}
declare module 'realm/react-native/listview.js' {
  declare module.exports: $Exports<'realm/react-native/listview'>;
}
declare module 'realm/scripts/check-environment.js' {
  declare module.exports: $Exports<'realm/scripts/check-environment'>;
}
declare module 'realm/scripts/download-realm.js' {
  declare module.exports: $Exports<'realm/scripts/download-realm'>;
}
declare module 'realm/scripts/handle-license-check.js' {
  declare module.exports: $Exports<'realm/scripts/handle-license-check'>;
}
declare module 'realm/scripts/prepublish.js' {
  declare module.exports: $Exports<'realm/scripts/prepublish'>;
}
declare module 'realm/scripts/react-tests-android.js' {
  declare module.exports: $Exports<'realm/scripts/react-tests-android'>;
}
declare module 'realm/scripts/test-ros-server.js' {
  declare module.exports: $Exports<'realm/scripts/test-ros-server'>;
}
