// flow-typed signature: 248a8cde218a627586368a7f414967ab
// flow-typed version: <<STUB>>/tiny-emitter_v2.1.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tiny-emitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tiny-emitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tiny-emitter/dist/tinyemitter' {
  declare module.exports: any;
}

declare module 'tiny-emitter/dist/tinyemitter.min' {
  declare module.exports: any;
}

declare module 'tiny-emitter/instance' {
  declare module.exports: any;
}

declare module 'tiny-emitter/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tiny-emitter/dist/tinyemitter.js' {
  declare module.exports: $Exports<'tiny-emitter/dist/tinyemitter'>;
}
declare module 'tiny-emitter/dist/tinyemitter.min.js' {
  declare module.exports: $Exports<'tiny-emitter/dist/tinyemitter.min'>;
}
declare module 'tiny-emitter/index' {
  declare module.exports: $Exports<'tiny-emitter'>;
}
declare module 'tiny-emitter/index.js' {
  declare module.exports: $Exports<'tiny-emitter'>;
}
declare module 'tiny-emitter/instance.js' {
  declare module.exports: $Exports<'tiny-emitter/instance'>;
}
declare module 'tiny-emitter/test/index' {
  declare module.exports: $Exports<'tiny-emitter/test'>;
}
declare module 'tiny-emitter/test/index.js' {
  declare module.exports: $Exports<'tiny-emitter/test'>;
}
