// flow-typed signature: 6da9d769ca453daaf4952b81a62999d1
// flow-typed version: <<STUB>>/topojson-client_v3.1.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'topojson-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'topojson-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'topojson-client/dist/topojson-client' {
  declare module.exports: any;
}

declare module 'topojson-client/dist/topojson-client.min' {
  declare module.exports: any;
}

declare module 'topojson-client/src/bbox' {
  declare module.exports: any;
}

declare module 'topojson-client/src/bisect' {
  declare module.exports: any;
}

declare module 'topojson-client/src/feature' {
  declare module.exports: any;
}

declare module 'topojson-client/src/identity' {
  declare module.exports: any;
}

declare module 'topojson-client/src' {
  declare module.exports: any;
}

declare module 'topojson-client/src/merge' {
  declare module.exports: any;
}

declare module 'topojson-client/src/mesh' {
  declare module.exports: any;
}

declare module 'topojson-client/src/neighbors' {
  declare module.exports: any;
}

declare module 'topojson-client/src/quantize' {
  declare module.exports: any;
}

declare module 'topojson-client/src/reverse' {
  declare module.exports: any;
}

declare module 'topojson-client/src/stitch' {
  declare module.exports: any;
}

declare module 'topojson-client/src/transform' {
  declare module.exports: any;
}

declare module 'topojson-client/src/untransform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'topojson-client/dist/topojson-client.js' {
  declare module.exports: $Exports<'topojson-client/dist/topojson-client'>;
}
declare module 'topojson-client/dist/topojson-client.min.js' {
  declare module.exports: $Exports<'topojson-client/dist/topojson-client.min'>;
}
declare module 'topojson-client/src/bbox.js' {
  declare module.exports: $Exports<'topojson-client/src/bbox'>;
}
declare module 'topojson-client/src/bisect.js' {
  declare module.exports: $Exports<'topojson-client/src/bisect'>;
}
declare module 'topojson-client/src/feature.js' {
  declare module.exports: $Exports<'topojson-client/src/feature'>;
}
declare module 'topojson-client/src/identity.js' {
  declare module.exports: $Exports<'topojson-client/src/identity'>;
}
declare module 'topojson-client/src/index' {
  declare module.exports: $Exports<'topojson-client/src'>;
}
declare module 'topojson-client/src/index.js' {
  declare module.exports: $Exports<'topojson-client/src'>;
}
declare module 'topojson-client/src/merge.js' {
  declare module.exports: $Exports<'topojson-client/src/merge'>;
}
declare module 'topojson-client/src/mesh.js' {
  declare module.exports: $Exports<'topojson-client/src/mesh'>;
}
declare module 'topojson-client/src/neighbors.js' {
  declare module.exports: $Exports<'topojson-client/src/neighbors'>;
}
declare module 'topojson-client/src/quantize.js' {
  declare module.exports: $Exports<'topojson-client/src/quantize'>;
}
declare module 'topojson-client/src/reverse.js' {
  declare module.exports: $Exports<'topojson-client/src/reverse'>;
}
declare module 'topojson-client/src/stitch.js' {
  declare module.exports: $Exports<'topojson-client/src/stitch'>;
}
declare module 'topojson-client/src/transform.js' {
  declare module.exports: $Exports<'topojson-client/src/transform'>;
}
declare module 'topojson-client/src/untransform.js' {
  declare module.exports: $Exports<'topojson-client/src/untransform'>;
}
