// flow-typed signature: 1cc2069ab1780ca115c5df1be068ff5f
// flow-typed version: <<STUB>>/utm-latlng_v1.0.5/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utm-latlng'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'utm-latlng' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utm-latlng/UTMLatLng' {
  declare module.exports: any;
}

declare module 'utm-latlng/UTMLatLngFront' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utm-latlng/UTMLatLng.js' {
  declare module.exports: $Exports<'utm-latlng/UTMLatLng'>;
}
declare module 'utm-latlng/UTMLatLngFront.js' {
  declare module.exports: $Exports<'utm-latlng/UTMLatLngFront'>;
}
