// flow-typed signature: cec33c2c4ff134d8c4b634f42c91404a
// flow-typed version: <<STUB>>/@mapbox/geojson-area_v0.2.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/geojson-area'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/geojson-area' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/geojson-area/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/geojson-area/index' {
  declare module.exports: $Exports<'@mapbox/geojson-area'>;
}
declare module '@mapbox/geojson-area/index.js' {
  declare module.exports: $Exports<'@mapbox/geojson-area'>;
}
declare module '@mapbox/geojson-area/test/basic.js' {
  declare module.exports: $Exports<'@mapbox/geojson-area/test/basic'>;
}
