// flow-typed signature: f8af9ac796a1dc7b3be53d63f7ce711a
// flow-typed version: <<STUB>>/@mapbox/tilebelt_v1.0.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/tilebelt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/tilebelt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/tilebelt/bench' {
  declare module.exports: any;
}

declare module '@mapbox/tilebelt/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/tilebelt/bench.js' {
  declare module.exports: $Exports<'@mapbox/tilebelt/bench'>;
}
declare module '@mapbox/tilebelt/index' {
  declare module.exports: $Exports<'@mapbox/tilebelt'>;
}
declare module '@mapbox/tilebelt/index.js' {
  declare module.exports: $Exports<'@mapbox/tilebelt'>;
}
declare module '@mapbox/tilebelt/test.js' {
  declare module.exports: $Exports<'@mapbox/tilebelt/test'>;
}
