// flow-typed signature: 09d12500ca29bf761008bb5f75e10283
// flow-typed version: <<STUB>>/@mapbox/togeojson_v0.16.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/togeojson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/togeojson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/togeojson/togeojson' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/togeojson/togeojson.js' {
  declare module.exports: $Exports<'@mapbox/togeojson/togeojson'>;
}
