source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

# https://github.com/airbnb/react-native-maps/issues/718#issuecomment-295585410
target 'ForestWatcher' do

  pod 'AppAuth'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  # pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  # pod 'CodePush', :path => '../node_modules/react-native-code-push'

  ## Pods for AppCenter
  pod 'AppCenterReactNativeShared', '~> 1.10.0'

  ## react-native-maps dependencies
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-safe-area', :path => '../node_modules/react-native-safe-area'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
          if target.name == "React"
              target.remove_from_project
          end
          target.build_configurations.each do |config|
              config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          end
      end
  end
end
