source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# https://github.com/airbnb/react-native-maps/issues/718#issuecomment-295585410
target 'ForestWatcher' do

  pod 'GoogleMaps'
  pod 'AppAuth'
  pod 'FBSDKLoginKit'

  # pod 'CodePush', :path => '../node_modules/react-native-code-push'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
              config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
         end
    end
  end
end
