// flow-typed signature: 8943cafbec908cf3ef96292c6f21dce2
// flow-typed version: <<STUB>>/@tmcw/togeojson_v4.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tmcw/togeojson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tmcw/togeojson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tmcw/togeojson/dist/togeojson.es' {
  declare module.exports: any;
}

declare module '@tmcw/togeojson/dist/togeojson' {
  declare module.exports: any;
}

declare module '@tmcw/togeojson/dist/togeojson.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tmcw/togeojson/dist/togeojson.es.js' {
  declare module.exports: $Exports<'@tmcw/togeojson/dist/togeojson.es'>;
}
declare module '@tmcw/togeojson/dist/togeojson.js' {
  declare module.exports: $Exports<'@tmcw/togeojson/dist/togeojson'>;
}
declare module '@tmcw/togeojson/dist/togeojson.umd.js' {
  declare module.exports: $Exports<'@tmcw/togeojson/dist/togeojson.umd'>;
}
