# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

IPA_PATH="./ForestWatcher.ipa"

default_platform(:ios)

platform :ios do
  desc "Deploy a new version to the Apple Store"
  lane :deploy do
    increment_build_number(xcodeproj: "ForestWatcher.xcodeproj")
    cocoapods()
    gym(scheme: "ForestWatcher")
    upload_to_app_store(
      ipa: IPA_PATH
    )
    notification(
      title: "iOS deploy",
      subtitle: "Finished and uploaded to apple store",
      message: "Click to review it",
      open: "https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app"
    )
  end
end
