# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

IPA_PATH="./ForestWatcher.ipa"

default_platform(:ios)

platform :ios do
  desc "Submit a new beta build to app center"
  lane :beta do
    increment_build_number(xcodeproj: "ForestWatcher.xcodeproj")
    cocoapods()
    gym(export_method: "ad-hoc")
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: "ForestWatcher-iOS",
      ipa: IPA_PATH
    )
    notification(
      title: "iOS beta",
      subtitle: "Finished and uploaded to app center",
      message: "Click to review it",
      open: "https://appcenter.ms/users/forestwatchervizz/apps/ForestWatcher-iOS/distribute/releases"
    )
  end

  desc "Deploy a new version to the Apple Store"
  lane :deploy do
    cocoapods()
    gym(scheme: "ForestWatcher")
    upload_to_app_store(
      ipa: IPA_PATH
    )
    notification(
      title: "iOS deploy",
      subtitle: "Finished and uploaded to apple store",
      message: "Click to review it",
      open: "https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app"
    )
  end
end
