// flow-typed signature: eb8342976e9e95b9ac1dcffd8cf6030c
// flow-typed version: <<STUB>>/@redux-offline/redux-offline_v2.5.2-native.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@redux-offline/redux-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@redux-offline/redux-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@redux-offline/redux-offline/flow-typed/npm/redux_v4.x.x' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/flow-typed/npm/redux-logger_vx.x.x' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/actions' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/config' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/constants' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/defaultCommit' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/defaultRollback' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/detectNetwork' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/detectNetwork.native' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/discard' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/effect' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/offlineStateLens' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/persist' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/persist.native' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/persistAutoRehydrate' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/queue' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/defaults/retry' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/middleware' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/offlineActionTracker' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/send' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/types' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/lib/updater' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/__tests__/defaults/discard' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/__tests__/defaults/effect' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/__tests__' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/__tests__/middleware' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/__tests__/offlineActionTracker' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/__tests__/send' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/actions' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/config' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/constants' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/defaultCommit' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/defaultRollback' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/detectNetwork' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/detectNetwork.native' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/discard' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/effect' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/offlineStateLens' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/persist' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/persist.native' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/persistAutoRehydrate' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/queue' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/defaults/retry' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/middleware' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/offlineActionTracker' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/send' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/types' {
  declare module.exports: any;
}

declare module '@redux-offline/redux-offline/src/updater' {
  declare module.exports: any;
}

// Filename aliases
declare module '@redux-offline/redux-offline/flow-typed/npm/redux_v4.x.x.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/flow-typed/npm/redux_v4.x.x'>;
}
declare module '@redux-offline/redux-offline/flow-typed/npm/redux-logger_vx.x.x.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/flow-typed/npm/redux-logger_vx.x.x'>;
}
declare module '@redux-offline/redux-offline/lib/actions.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/actions'>;
}
declare module '@redux-offline/redux-offline/lib/config.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/config'>;
}
declare module '@redux-offline/redux-offline/lib/constants.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/constants'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/defaultCommit.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/defaultCommit'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/defaultRollback.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/defaultRollback'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/detectNetwork.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/detectNetwork'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/detectNetwork.native.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/detectNetwork.native'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/discard.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/discard'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/effect.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/effect'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/index' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/index.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/offlineStateLens.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/offlineStateLens'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/persist.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/persist'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/persist.native.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/persist.native'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/persistAutoRehydrate.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/persistAutoRehydrate'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/queue.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/queue'>;
}
declare module '@redux-offline/redux-offline/lib/defaults/retry.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/defaults/retry'>;
}
declare module '@redux-offline/redux-offline/lib/index' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib'>;
}
declare module '@redux-offline/redux-offline/lib/index.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib'>;
}
declare module '@redux-offline/redux-offline/lib/middleware.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/middleware'>;
}
declare module '@redux-offline/redux-offline/lib/offlineActionTracker.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/offlineActionTracker'>;
}
declare module '@redux-offline/redux-offline/lib/send.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/send'>;
}
declare module '@redux-offline/redux-offline/lib/types.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/types'>;
}
declare module '@redux-offline/redux-offline/lib/updater.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/lib/updater'>;
}
declare module '@redux-offline/redux-offline/src/__tests__/defaults/discard.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/__tests__/defaults/discard'>;
}
declare module '@redux-offline/redux-offline/src/__tests__/defaults/effect.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/__tests__/defaults/effect'>;
}
declare module '@redux-offline/redux-offline/src/__tests__/index' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/__tests__'>;
}
declare module '@redux-offline/redux-offline/src/__tests__/index.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/__tests__'>;
}
declare module '@redux-offline/redux-offline/src/__tests__/middleware.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/__tests__/middleware'>;
}
declare module '@redux-offline/redux-offline/src/__tests__/offlineActionTracker.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/__tests__/offlineActionTracker'>;
}
declare module '@redux-offline/redux-offline/src/__tests__/send.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/__tests__/send'>;
}
declare module '@redux-offline/redux-offline/src/actions.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/actions'>;
}
declare module '@redux-offline/redux-offline/src/config.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/config'>;
}
declare module '@redux-offline/redux-offline/src/constants.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/constants'>;
}
declare module '@redux-offline/redux-offline/src/defaults/defaultCommit.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/defaultCommit'>;
}
declare module '@redux-offline/redux-offline/src/defaults/defaultRollback.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/defaultRollback'>;
}
declare module '@redux-offline/redux-offline/src/defaults/detectNetwork.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/detectNetwork'>;
}
declare module '@redux-offline/redux-offline/src/defaults/detectNetwork.native.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/detectNetwork.native'>;
}
declare module '@redux-offline/redux-offline/src/defaults/discard.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/discard'>;
}
declare module '@redux-offline/redux-offline/src/defaults/effect.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/effect'>;
}
declare module '@redux-offline/redux-offline/src/defaults/index' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults'>;
}
declare module '@redux-offline/redux-offline/src/defaults/index.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults'>;
}
declare module '@redux-offline/redux-offline/src/defaults/offlineStateLens.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/offlineStateLens'>;
}
declare module '@redux-offline/redux-offline/src/defaults/persist.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/persist'>;
}
declare module '@redux-offline/redux-offline/src/defaults/persist.native.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/persist.native'>;
}
declare module '@redux-offline/redux-offline/src/defaults/persistAutoRehydrate.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/persistAutoRehydrate'>;
}
declare module '@redux-offline/redux-offline/src/defaults/queue.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/queue'>;
}
declare module '@redux-offline/redux-offline/src/defaults/retry.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/defaults/retry'>;
}
declare module '@redux-offline/redux-offline/src/index' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src'>;
}
declare module '@redux-offline/redux-offline/src/index.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src'>;
}
declare module '@redux-offline/redux-offline/src/middleware.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/middleware'>;
}
declare module '@redux-offline/redux-offline/src/offlineActionTracker.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/offlineActionTracker'>;
}
declare module '@redux-offline/redux-offline/src/send.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/send'>;
}
declare module '@redux-offline/redux-offline/src/types.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/types'>;
}
declare module '@redux-offline/redux-offline/src/updater.js' {
  declare module.exports: $Exports<'@redux-offline/redux-offline/src/updater'>;
}
