# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

APK_PATH="./app/build/outputs/apk/release/app-release.apk"

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_code(
      gradle_file_path: "app/build.gradle"
    )
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
      apk: APK_PATH
    )
    notification(
      title: "Android deploy",
      subtitle: "Finished and uploaded to play store",
      message: "Click to review it",
      open: "https://play.google.com/apps/publish"
    )
  end
end
